[package]
name = "zen-loader"
version = "0.1.0"
authors = ["MordragT <scrat_games@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zen-archive = { path = "crates/zen-archive" }
zen-material = { path = "crates/zen-material" }
zen-mesh = { path = "crates/zen-mesh" }
zen-parser = { path = "crates/zen-parser" }
zen-texture = { path = "crates/zen-texture" }

