[package]
name = "zen-mesh"
version = "0.1.0"
authors = ["MordragT <scrat_games@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.115", features = ["derive"] }
gltf-json = "0.15.2"
gltf = "0.15.2"
tri-mesh = "0.5.0"
zen-parser = { path = "../zen-parser" }
zen-types = { path = "../zen-types" }
zen-material = { path = "../zen-material" }
vek = { version = "0.12.0", features = ["serde"] }

[dev-dependencies]
zen-archive = { path = "../zen-archive" }