//! Definitions for compressed ZenGin Textures (.tex)
//! Gothic stores its textures in a proprietary format called ZTEX, which is basically DDS
//! with a different Header and some minor other modifications.

//! Those ZTEX-files are generated by the game by converting TGA files, which can be seen as
//! caching mechanism. Therefore, in the other game files, the original TGA-name will be used.

//! To still load the correct file, we have to convert the input filename of "SAMPLE.TGA" into
//! "SAMPLE-C.TEX", which is the compiled ZTEX file.

//! In case there is no such compiled ZTEX file, we will try to load the original TGA file instead.

mod asset_loader;
mod format;
mod header;
mod plugin;
mod texture;

pub mod error;

pub use asset_loader::*;
pub use format::ZTexFormat;
pub use plugin::ZTexPlugin;
pub use texture::ZTex;
