[package]
name = "zen-input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#zen-ects = { path = "../zen-ects" }
hecs = "0.6.5"