[package]
name = "zen-vdfs"
version = "0.1.0"
edition = "2021"

[dependencies]
zen-parser = { path = "../zen-parser" }
serde.workspace = true
thiserror.workspace = true
bevy.workspace = true

[dev-dependencies]
zen-core = { path = "../zen-core" }
