[package]
name = "zen-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hecs = "0.7"
ultraviolet = "0.8"
zen-model = { path = "../zen-model" }